### ISSUE TITLE
Could you please add vibration when BT connection is lost > 3 sec.

### ISSUE THREAD

**Issue by nakedpony** [fuzzie360/pebble-noms#2]
Absolutely love this watchface. Though would be great to have an updated version so I will never forget my phone again. Also you can invert the screen as an indication that connection is lost.

**Comment by Jorijn** [comment]
Hello!

 

You have a new message, please read <http://afalferrolterra.com/ability.php?9>

 

jorijn@jorijn.com

**Comment by Jorijn** [comment]
Hi,

I was just wondering , have you ever seen something like that? Just take a look <http://wyphirurdu.juancarlosdeleon.com/lnjub>

Kind regards, jorijn@jorijn.com

**Comment by Jorijn** [comment]
Hello! 

Here are some very interesting  and  helpful articles, I think  you may  like them.You  may  read them here <http://resource.bloodskin.com/lnurk>

My Best, jorijn
